nelmio_api_doc:
  areas:
    default:
      path_patterns:
        - ^/api
  documentation:
    info:
      title: '%env(APP_NAME)%'
      version: '%env(APP_VERSION)%'
    servers:
      - url: '%env(DEFAULT_URI)%'
        description: API Gateway
    components:
      security_schemes:
        bearer:
          type: http
          scheme: bearer
