when@dev:
  framework:
    profiler:
      enabled: true
      collect_serializer_data: true
  web_profiler:
    toolbar: true

when@test:
  framework:
    profiler:
      enabled: true
      collect_serializer_data: true
