services:
  application:
    build: .
    hostname: application
    container_name: "${APP_NAME}-application"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "true" ]
    ports:
      - "${APP_PORT:-80}:80"
    depends_on:
      - mailcatcher
      - postgres
      - rabbitmq
      - redis
    volumes:
      - ./:/opt/project:consistent
    networks:
      internal:

  messenger:
    build: .
    hostname: messenger
    command: messenger
    container_name: "${APP_NAME}-messenger"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "true" ]
    depends_on:
      - application
      - mailcatcher
      - postgres
      - rabbitmq
      - redis
    volumes:
      - ./:/opt/project:consistent
    networks:
      internal:

  migration:
    build: .
    hostname: migration
    command: migration
    container_name: "${APP_NAME}-migration"
    healthcheck:
      test: [ "CMD", "true" ]
    depends_on:
      - application
      - postgres
    volumes:
      - ./:/opt/project:consistent
    networks:
      internal:

  redis:
    image: redis:latest
    hostname: redis
    container_name: "${APP_NAME}-redis"
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      internal:

  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    container_name: "${APP_NAME}-rabbitmq"
    restart: unless-stopped
    ports:
      - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      internal:

  postgres:
    image: postgres:18.1
    hostname: postgres
    container_name: "${APP_NAME}-postgres"
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: symfony
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      internal:

  mailcatcher:
    image: opifex/mailcatcher:latest
    hostname: mailcatcher
    container_name: "${APP_NAME}-mailcatcher"
    restart: unless-stopped
    ports:
      - "1088:1080"
    networks:
      internal:

volumes:
  postgres:
  rabbitmq:
  redis:

networks:
  internal:
    name: "${APP_NAME}-network"
