when@dev:
  app_profiler_wdt:
    resource: '@WebProfilerBundle/Resources/config/routing/wdt.php'
    prefix: /_wdt

  app_profiler_ui:
    resource: '@WebProfilerBundle/Resources/config/routing/profiler.php'
    prefix: /_profiler
